name: "Hugo Build"
description: "Builds the website with Hugo"
runs:
  using: "composite"

  steps:
    - name: "Download Hugo"
      shell: "bash"
      run: "wget https://github.com/gohugoio/hugo/releases/download/v0.141.0/hugo_extended_0.141.0_linux-amd64.deb"

    - name: "Install Hugo"
      shell: "bash"
      run: "sudo apt install ./hugo_extended_0.141.0_linux-amd64.deb"

    - name: "Build Site"
      shell: "bash"
      run: "hugo"
